
export const authorList = [
    "All Authors",
    "Unknown",

    "Kimura",
    "DELETE_CLUB",
    "BdcapTAS",
    "igntuL",
    "Bice",
    "mufattmf",
    "CrizpyCheese",
    "charlie",
    "Thoman",
    "ezmTAS",
    "Ibozz91",
    "MidnightEuphoria",
    "Oogy749",
    "Gl1tch3D",
    "Miku",
    "fabi",
    "LittleD3m0",
    "caleb",
    "xnferno",
    "faiby",
    "TTR_Mc 77",
    "Arkes",
    "trabadia",
    "Virtuoso",
    "threadd",
    
    "Alex",
    "plastorex",
    "Molosii",
    "XvX",
    "Thunder",
    "Don Johnson",
    "maB-TM",
    "Q0uut",
    "Jsap",
    "Winterly",
    "Lukalyc",
    "exlpt",
    "Shweetz",
    "Trinity",
    "angry_birds_45",
    "donadigo",
    "MasnySunshine",
    "Link",
    "Stuntlover",
    "gingerroar",
    "Dacuber",
    "GorillaKing",
    "andi",
    "didiking",
    "cj5716",
    "wildmagnusdk",
    "AurisTFG",
    "Linesight",
    "kram",
    "simo_900",
    "Drarker",
    "dimi",
    "ins",
    "Schmaniol",
    "casper",
    "gbod",
    "Louis",
    "goldenowl",
    "Wirtual",
    "Adrien",
    "Niro",
    "ben1996123",
    "SaiMoen",
    "Vogtek",
    "Faasquit",
    "Mizu",
    "HappyHunter",
    "Angecide",
    "Speedy0407",
    "Sokko",
    "Zytryhard",
    "G-Star",
    "hhh",
    "Versital",
    "Crayoon",
    "Speedy",
    "Kali",
    "Mango",
    "N-Jin",
    "Hefest",
    "Djafex",
    "dennis090",
    "Alexey Steen8",
    "tobynatoar",
    "Na'Guul",
    "DarkLink",
    "Elite Runner",
    "samel",
    "Bunji",
    "Meable",
    "Thoz",
    "Nersons",
    "LPNoNameGame",
    "Akantor",
    "Vlader",
    "Rohodez",
    "Speed",
    "Prow",
    "oli10",
    "Rollin",
    "sajrajt",
    "lambda",
    "aestas",
    "johalss",
    "Chung",
    "Twince",
    "Tracktor Fan",
    "raizo",
    "Nino",
    "fam.demon",
    "TheBoat11th",
    "Statikk",
    "Spuik",
    "Stanbay",
    "Tantalum Sulphide",
    "KrisFan27",
    "6MB11",
    "Wavyhertz",
    "carbide",
    "GarfieldTM",
    "Sneak",
    "Sneezu",
    "logout",
    "Yosh",
    "emerald_lag",
    "fluffy",
    "Frusty74",
    "f1uffy",
    "MB",
    "ComfyIvy",
    "Leva",
    "PhantmmSlide",
    "Rio",
    "linden",
    "lettuce5909",
    "Hardtack",
    "fwo johalss",
    "TM Chung",
    "Neko",
    "Lanz",
    "Bananaking",
    "Romoki.23",
    "KRONGTEKK",
    "Jiklim",
    "MakoTM",
    "Instable",
    "ZappZ",
    "VertexTM",
    "BugBear",
    "Iwcus",
    "Felippe",
    "Itamar67",
    "HbilTM",
    "Tortellini",
    "Artemis",
    "Phip",

] as const;

export type Author = (typeof authorList)[number];
