export type TasEntry = {
  track: string;
  time: string;
  vsRta: string;
  authors: string[];
  date: string;
  links: {
    video: string;
    replay: string;
    inputs: string;
  };
};

export type GameBoard = {
  slug: string;
  name: string;
  description: string;
  entries: TasEntry[];
};

export const leaderboards: GameBoard[] = [
  {
    slug: "tmnf",
    name: "TMNF",
    description: "Current WR TAS records per TMNF track, with video, replay and raw input links.",
    entries: [
  {
    track: "A01",
    time: "0:17.61",
    vsRta: "-6.16",
    authors: ["igntuL", "Na'Guul", "trabadia", "Lukalyc"],
    date: "2023-07-22",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "A02",
    time: "0:14.72",
    vsRta: "-0.54",
    authors: ["CrizpyCheese"],
    date: "2026-03-15",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "A03",
    time: "0:17.43",
    vsRta: "-0.80",
    authors: ["Winterly", "trabadia"],
    date: "2025-01-22",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "A04",
    time: "0:5.73",
    vsRta: "-0.05",
    authors: ["Don Johnson"],
    date: "2024-12-05",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "A05",
    time: "0:15.63",
    vsRta: "-0.42",
    authors: ["CrizpyCheese"],
    date: "2026-03-15",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "A06",
    time: "0:20.86",
    vsRta: "-6.64",
    authors: ["Thoman", "mufattmf", "igntuL", "CrizpyCheese"],
    date: "2024-03-02",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "A07",
    time: "0:22.46",
    vsRta: "-3.72",
    authors: ["Bice", "Winterly"],
    date: "2024-08-26",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "A08",
    time: "0:31.32",
    vsRta: "-24.39",
    authors: ["charlie"],
    date: "2026-04-21",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "A09",
    time: "0:16.77",
    vsRta: "-7.47",
    authors: ["Bice"],
    date: "2025-11-26",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "A10",
    time: "0:8.71",
    vsRta: "-0.09",
    authors: ["Winterly"],
    date: "2025-02-15",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "A11",
    time: "0:17.83",
    vsRta: "-0.52",
    authors: ["CrizpyCheese"],
    date: "2026-03-15",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "A12",
    time: "0:8.85",
    vsRta: "-1.56",
    authors: ["Meable"],
    date: "2026-02-19",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "A13",
    time: "0:16.84",
    vsRta: "-10.44",
    authors: ["igntuL", "Bice", "MidnightEuphoria"],
    date: "2026-03-01",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "A14",
    time: "0:18.87",
    vsRta: "-1.30",
    authors: ["ezmTAS"],
    date: "2025-09-29",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "A15",
    time: "0:22.26",
    vsRta: "-2.05",
    authors: ["CrizpyCheese", "plastorex", "gingerroar", "mufattmf"],
    date: "2024-03-01",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B01",
    time: "0:22.05",
    vsRta: "-3.18",
    authors: ["didiking", "mufattmf", "BdcapTAS"],
    date: "2026-02-27",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B02",
    time: "0:22.85",
    vsRta: "-2.06",
    authors: ["Bice", "BdcapTAS", "ezmTAS", "charlie"],
    date: "2025-04-15",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B03",
    time: "0:22.10",
    vsRta: "-2.22",
    authors: ["ezmTAS", "charlie"],
    date: "2025-05-28",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B04",
    time: "0:5.45",
    vsRta: "-7.02",
    authors: ["Thoman"],
    date: "2025-07-20",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B05",
    time: "0:22.99",
    vsRta: "-2.02",
    authors: ["didiking"],
    date: "2023-05-21",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B06",
    time: "0:25.79",
    vsRta: "-0.91",
    authors: ["threadd", "Kimura", "BdcapTAS"],
    date: "2026-01-29",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B07",
    time: "0:23.97",
    vsRta: "-3.37",
    authors: ["mufattmf", "Thoman"],
    date: "2025-02-25",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B08",
    time: "0:43.45",
    vsRta: "-44.74",
    authors: ["Miku", "mufattmf", "Kimura", "Thoman", "xnferno"],
    date: "2026-01-01",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B09",
    time: "0:12.97",
    vsRta: "-0.03",
    authors: ["igntuL"],
    date: "2024-02-28",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B10",
    time: "0:18.67",
    vsRta: "-15.77",
    authors: ["Virtuoso", "Molosii"],
    date: "2023-08-11",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B11",
    time: "0:26.60",
    vsRta: "-3.02",
    authors: ["Oogy749", "MidnightEuphoria"],
    date: "2026-04-03",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B12",
    time: "0:19.65",
    vsRta: "-19.34",
    authors: ["Lukalyc", "charlie"],
    date: "2025-03-17",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B13",
    time: "0:19.26",
    vsRta: "-5.65",
    authors: ["threadd", "Molosii"],
    date: "2023-07-29",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B14",
    time: "0:14.18",
    vsRta: "-16.44",
    authors: ["igntuL", "faiby"],
    date: "2026-04-28",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B15",
    time: "0:20.60",
    vsRta: "-17.88",
    authors: ["igntuL", "mufattmf", "didiking"],
    date: "2024-07-05",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C01",
    time: "0:18.73",
    vsRta: "-7.90",
    authors: ["mufattmf", "igntuL"],
    date: "2024-02-24",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C02",
    time: "0:30.12",
    vsRta: "-7.77",
    authors: ["Molosii"],
    date: "2023-06-29",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C03",
    time: "0:10.03",
    vsRta: "-2.01",
    authors: ["charlie", "ezmTAS", "igntuL"],
    date: "2026-04-13",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C04",
    time: "0:19.00",
    vsRta: "-15.61",
    authors: ["charlie"],
    date: "2026-01-28",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C05",
    time: "0:59.10",
    vsRta: "-44.17",
    authors: ["threadd", "mufattmf", "Miku"],
    date: "2023-12-23",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C06",
    time: "0:28.36",
    vsRta: "-23.07",
    authors: ["exlpt"],
    date: "2023-07-12",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C07",
    time: "0:27.12",
    vsRta: "-8.34",
    authors: ["CrizpyCheese", "charlie", "ezmTAS"],
    date: "2024-08-22",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C08",
    time: "0:11.75",
    vsRta: "-13.18",
    authors: ["Don Johnson"],
    date: "2024-08-21",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C09",
    time: "0:24.70",
    vsRta: "-14.51",
    authors: ["threadd"],
    date: "2023-01-21",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C10",
    time: "0:10.87",
    vsRta: "-0.78",
    authors: ["Don Johnson", "igntuL"],
    date: "2025-08-21",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C11",
    time: "0:22.24",
    vsRta: "-23.64",
    authors: ["Miku", "charlie"],
    date: "2026-01-23",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C12",
    time: "0:17.18",
    vsRta: "-11.69",
    authors: ["Jsap"],
    date: "2023-12-05",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C13",
    time: "0:17.36",
    vsRta: "-22.77",
    authors: ["Don Johnson"],
    date: "2022-02-08",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C14",
    time: "0:36.87",
    vsRta: "-1:00.78",
    authors: ["mufattmf", "Stuntlover"],
    date: "2024-02-22",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C15",
    time: "0:27.58",
    vsRta: "-19.09",
    authors: ["BdcapTAS", "Lukalyc"],
    date: "2026-02-14",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D01",
    time: "1:22.55",
    vsRta: "-53.08",
    authors: ["threadd", "Louis", "Bice"],
    date: "2022-10-12",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D02",
    time: "0:18.26",
    vsRta: "-26.98",
    authors: ["charlie"],
    date: "2025-03-22",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D03",
    time: "0:8.61",
    vsRta: "-5.63",
    authors: ["Don Johnson", "Virtuoso", "MidnightEuphoria"],
    date: "2026-02-10",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D04",
    time: "0:24.05",
    vsRta: "-17.63",
    authors: ["mufattmf", "Thoman"],
    date: "2025-02-24",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D05",
    time: "0:27.93",
    vsRta: "-29.75",
    authors: ["Dacuber"],
    date: "2025-01-29",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D06",
    time: "0:21.65",
    vsRta: "-34.99",
    authors: ["charlie", "goldenowl"],
    date: "2024-12-06",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D07",
    time: "0:19.67",
    vsRta: "-26.12",
    authors: ["charlie", "maB-TM", "Sneak", "Sheezu", "mufattmf", "logout", "BdcapTAS", "goldenowl"],
    date: "2024-09-25",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D08",
    time: "0:26.93",
    vsRta: "-20.40",
    authors: ["Lukalyc", "threadd"],
    date: "2024-03-05",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D09",
    time: "0:26.19",
    vsRta: "-14.27",
    authors: ["Gl1tch3D", "GorillaKing", "Jsap", "LittleD3m0", "mufattmf", "maB-TM", "ezmTAS", "Kimura"],
    date: "2026-01-09",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D10",
    time: "0:29.37",
    vsRta: "-13.93",
    authors: ["Virtuoso", "Jsap", "Thoman", "mufattmf"],
    date: "2023-06-04",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D11",
    time: "0:8.94",
    vsRta: "-0.23",
    authors: ["faiby"],
    date: "2026-01-01",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D12",
    time: "0:19.51",
    vsRta: "-18.85",
    authors: ["threadd"],
    date: "2023-05-06",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D13",
    time: "0:29.59",
    vsRta: "-32.94",
    authors: ["Bice", "CrizpyCheese", "mufattmf", "goldenowl"],
    date: "2024-06-23",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D14",
    time: "0:41.94",
    vsRta: "-1:52.07",
    authors: ["charlie", "Miku", "Kimura", "Bice", "TTR_Mc 77", "Thoman", "Louis", "BdcapTAS"],
    date: "2025-10-27",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D15",
    time: "3:07.61",
    vsRta: "-3:53.85",
    authors: ["GorillaKing", "Faasquit", "ezmTAS"],
    date: "2024-07-02",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "E01",
    time: "0:18.07",
    vsRta: "-25.50",
    authors: ["threadd", "Virtuoso"],
    date: "2023-07-29",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "E02",
    time: "0:44.43",
    vsRta: "-2:38.88",
    authors: ["Virtuoso"],
    date: "2022-08-27",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "E03",
    time: "2:45.62",
    vsRta: "-1:48.61",
    authors: ["Lukalyc"],
    date: "2024-11-14",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "E04",
    time: "0:42.54",
    vsRta: "-45.94",
    authors: ["threadd", "mufattmf"],
    date: "2024-01-07",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "E05",
    time: "18:29.59",
    vsRta: "-34:55.55",
    authors: ["mufattmf", "igntuL", "Vogtek", "charlie", "Jsap", "Thoman"],
    date: "2025-05-17",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
    ],
  },
  {
    slug: "tmnf-no-cut",
    name: "TMNF No Cut",
    description: "No cut tracks for TMNF with TAS leaderboards.",
    entries: [
      {
        track: "A02 - No Cut",
        time: "1:15.23",
        vsRta: "-1.45",
        authors: ["SpeedDemon"],
        date: "2026-04-20",
        links: {
          video: "https://youtu.be/example-video-eswc",
          replay: "https://drive.google.com/example-replay-eswc",
          inputs: "https://your-site.example/inputs/eswc-2008",
        },
      },
    ],
  },
  {
    slug: "tmn-eswc",
    name: "TMN ESWC",
    description: "ESWC championship tracks with TAS leaderboards.",
    entries: [
  {
    track: "A-0",
    time: "4.38",
    vsRta: "-0.01",
    authors: ["Gl1tch3D", "Virtuoso", "Shweetz", "trabadia"],
    date: "2021-12-22",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "A-1",
    time: "4.62",
    vsRta: "0.00",
    authors: ["Q0uut"],
    date: "2023-09-07",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "A-2",
    time: "7.37",
    vsRta: "-0.02",
    authors: ["BdcapTAS"],
    date: "2025-06-15",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "A-3",
    time: "9.34",
    vsRta: "-0.07",
    authors: ["igntuL"],
    date: "2025-06-19",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "A-4",
    time: "7.38",
    vsRta: "-0.01",
    authors: ["Thoman"],
    date: "2024-04-15",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "A-5",
    time: "6.47",
    vsRta: "0.00",
    authors: ["Kimura"],
    date: "2022-06-19",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "A-7",
    time: "10.09",
    vsRta: "-0.01",
    authors: ["Alex", "DELETE_CLUB"],
    date: "2024-03-22",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "A-8",
    time: "9.42",
    vsRta: "-0.29",
    authors: ["igntuL", "MidnightEuphoria", "caleb"],
    date: "2026-04-26",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B-0",
    time: "8.32",
    vsRta: "-2.48",
    authors: ["igntuL"],
    date: "2026-04-07",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B-1",
    time: "9.22",
    vsRta: "-0.18",
    authors: ["igntuL"],
    date: "2026-04-07",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B-2",
    time: "13.67",
    vsRta: "-0.08",
    authors: ["Bice", "Gl1tch3D", "BdcapTAS"],
    date: "2026-05-01",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B-3",
    time: "13.10",
    vsRta: "-0.08",
    authors: ["xnferno"],
    date: "2026-04-27",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B-4",
    time: "6.53",
    vsRta: "-0.01",
    authors: ["Thoman"],
    date: "2026-04-25",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B-5",
    time: "15.64",
    vsRta: "-2.12",
    authors: ["ezmTAS", "MidnightEuphoria"],
    date: "2025-07-29",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B-6",
    time: "11.01",
    vsRta: "-0.21",
    authors: ["xnferno", "faiby", "igntuL"],
    date: "2026-03-23",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B-7",
    time: "14.28",
    vsRta: "-0.19",
    authors: ["igntuL"],
    date: "2025-06-17",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B-8",
    time: "13.47",
    vsRta: "-0.03",
    authors: ["BdcapTAS"],
    date: "2025-04-12",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "B-9",
    time: "14.19",
    vsRta: "-0.02",
    authors: ["BdcapTAS"],
    date: "2024-11-30",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C-0",
    time: "18.85",
    vsRta: "-0.09",
    authors: ["BdcapTAS"],
    date: "2026-01-23",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C-1",
    time: "20.93",
    vsRta: "-0.02",
    authors: ["BdcapTAS"],
    date: "2026-04-30",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C-2",
    time: "9.16",
    vsRta: "-0.05",
    authors: ["igntuL"],
    date: "2026-04-03",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C-3",
    time: "11.35",
    vsRta: "-0.68",
    authors: ["Alex", "plastorex"],
    date: "2023-07-26",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C-4",
    time: "13.72",
    vsRta: "-0.04",
    authors: ["Leva"],
    date: "2024-08-29",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C-5",
    time: "14.86",
    vsRta: "-0.34",
    authors: ["angry_birds_45", "Virtuoso"],
    date: "2022-03-09",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C-6",
    time: "13.24",
    vsRta: "-0.08",
    authors: ["igntuL"],
    date: "2026-04-07",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C-7",
    time: "9.07",
    vsRta: "-0.02",
    authors: ["igntuL"],
    date: "2026-03-24",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C-8",
    time: "8.95",
    vsRta: "-0.13",
    authors: ["TTR_Mc 77"],
    date: "2025-07-26",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "C-9",
    time: "17.53",
    vsRta: "-1.34",
    authors: ["PhantmmSlide"],
    date: "2025-08-31",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D-0",
    time: "7.99",
    vsRta: "-0.55",
    authors: ["Molosii"],
    date: "2022-03-18",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D-1",
    time: "19.88",
    vsRta: "-0.26",
    authors: ["igntuL"],
    date: "2026-04-07",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D-2",
    time: "12.93",
    vsRta: "-5.15",
    authors: ["charlie"],
    date: "2024-11-09",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D-3",
    time: "12.47",
    vsRta: "-0.93",
    authors: ["igntuL"],
    date: "2026-04-07",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D-4",
    time: "31.64",
    vsRta: "-7.17",
    authors: ["caleb", "igntuL", "MidnightEuphoria"],
    date: "2026-04-24",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D-5",
    time: "26.67",
    vsRta: "-0.42",
    authors: ["TTR_Mc 77"],
    date: "2025-07-01",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D-6",
    time: "3.94",
    vsRta: "-0.04",
    authors: ["charlie"],
    date: "2024-03-09",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D-7",
    time: "20.02",
    vsRta: "-1.34",
    authors: ["igntuL"],
    date: "2026-04-29",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D-8",
    time: "8.63",
    vsRta: "-0.02",
    authors: ["Gl1tch3D"],
    date: "2024-01-03",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "D-9",
    time: "15.52",
    vsRta: "-4.04",
    authors: ["MidnightEuphoria"],
    date: "2026-04-27",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "E-0",
    time: "32.64",
    vsRta: "-2.58",
    authors: ["angry_birds_45", "DELETE_CLUB"],
    date: "2023-07-26",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "E-1",
    time: "15.22",
    vsRta: "-4.81",
    authors: ["Bice"],
    date: "2022-12-12",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "E-2",
    time: "27.99",
    vsRta: "-7.95",
    authors: ["Winterly"],
    date: "2023-06-11",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "E-3",
    time: "23.20",
    vsRta: "-1.96",
    authors: ["MidnightEuphoria", "BdcapTAS"],
    date: "2026-02-19",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "E-4",
    time: "19.90",
    vsRta: "-0.56",
    authors: ["angry_birds_45"],
    date: "2021-07-24",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "E-5",
    time: "34.55",
    vsRta: "-19.11",
    authors: ["exlpt"],
    date: "2022-08-31",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "E-6",
    time: "30.61",
    vsRta: "-0.31",
    authors: ["Don Johnson"],
    date: "2021-10-06",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "E-7",
    time: "25.58",
    vsRta: "-14.62",
    authors: ["charlie"],
    date: "2025-12-29",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "E-8",
    time: "39.47",
    vsRta: "-3.14",
    authors: ["plastorex", "Alex"],
    date: "2023-07-29",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "E-9",
    time: "16.42",
    vsRta: "-0.61",
    authors: ["DELETE_CLUB"],
    date: "2023-03-07",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "F-0",
    time: "30.74",
    vsRta: "-4.14",
    authors: ["Jsap"],
    date: "2023-01-05",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "F-1",
    time: "27.02",
    vsRta: "-0.40",
    authors: ["angry_birds_45"],
    date: "2021-08-02",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "F-2",
    time: "46.73",
    vsRta: "-0.58",
    authors: ["angry_birds_45"],
    date: "2021-06-26",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "F-3",
    time: "11.86",
    vsRta: "-0.86",
    authors: ["igntuL"],
    date: "2026-03-27",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "F-4",
    time: "9.01",
    vsRta: "-4.03",
    authors: ["caleb"],
    date: "2026-03-21",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "F-5",
    time: "11.26",
    vsRta: "-13.07",
    authors: ["charlie", "Arkes"],
    date: "2025-03-05",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "F-7",
    time: "24.97",
    vsRta: "-2.97",
    authors: ["igntuL"],
    date: "2026-04-07",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "F-8",
    time: "17.78",
    vsRta: "-3.57",
    authors: ["Rio"],
    date: "2026-04-29",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "F-9",
    time: "27.64",
    vsRta: "-9.68",
    authors: ["Alex"],
    date: "2022-01-05",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "G-0",
    time: "12.71",
    vsRta: "-12.74",
    authors: ["LittleD3m0"],
    date: "2026-04-11",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "G-1",
    time: "50.89",
    vsRta: "-49.24",
    authors: ["MidnightEuphoria"],
    date: "2026-04-25",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "G-2",
    time: "6.61",
    vsRta: "-0.03",
    authors: ["Q0uut"],
    date: "2024-01-10",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "G-3",
    time: "23.03",
    vsRta: "-2.83",
    authors: ["igntuL"],
    date: "2026-03-28",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "G-4",
    time: "13.91",
    vsRta: "-7.30",
    authors: ["charlie"],
    date: "2024-02-24",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "G-5",
    time: "10.67",
    vsRta: "-0.03",
    authors: ["MidnightEuphoria"],
    date: "2026-04-24",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "G-6",
    time: "25.76",
    vsRta: "-27.97",
    authors: ["Thoz", "LittleD3m0"],
    date: "2026-04-28",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "G-7",
    time: "17.87",
    vsRta: "-3.15",
    authors: ["DELETE_CLUB", "dimi", "Shweetz", "Molosii"],
    date: "2022-04-17",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "G-8",
    time: "10.67",
    vsRta: "-17.48",
    authors: ["Bice"],
    date: "2026-04-28",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "G-9",
    time: "25.93",
    vsRta: "-2.38",
    authors: ["xnferno"],
    date: "2026-03-04",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "H-0",
    time: "34.23",
    vsRta: "-32.77",
    authors: ["Bice"],
    date: "2023-02-26",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "H-1",
    time: "31.18",
    vsRta: "-0.39",
    authors: ["angry_birds_45"],
    date: "2021-08-06",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "H-2",
    time: "42.91",
    vsRta: "-1.45",
    authors: ["Bunji"],
    date: "2025-05-24",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "H-3",
    time: "4.63",
    vsRta: "-0.01",
    authors: ["Winterly"],
    date: "2022-02-05",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "H-4",
    time: "45.97",
    vsRta: "-31.73",
    authors: ["ezmTAS"],
    date: "2024-01-30",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "H-5",
    time: "47.90",
    vsRta: "-1.17",
    authors: ["GorillaKing", "mufattmf", "ezmTAS"],
    date: "2024-03-13",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "H-6",
    time: "10.16",
    vsRta: "-2.38",
    authors: ["MidnightEuphoria"],
    date: "2026-04-05",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "H-7",
    time: "37.68",
    vsRta: "-4.19",
    authors: ["angry_birds_45"],
    date: "2021-08-08",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "H-8",
    time: "1:10.16",
    vsRta: "-17.43",
    authors: ["Alex"],
    date: "2022-01-06",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "H-9",
    time: "1:08.08",
    vsRta: "-1.65",
    authors: ["Shweetz"],
    date: "2021-07-17",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "I-0",
    time: "38.35",
    vsRta: "-7.99",
    authors: ["mufattmf"],
    date: "2023-10-15",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "I-2",
    time: "13.47",
    vsRta: "-15.32",
    authors: ["mufattmf"],
    date: "2024-01-31",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "I-3",
    time: "9.30",
    vsRta: "-2.35",
    authors: ["Alex"],
    date: "2025-06-25",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "I-4",
    time: "25.86",
    vsRta: "-0.91",
    authors: ["Kimura"],
    date: "2022-02-28",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "I-5",
    time: "43.81",
    vsRta: "-1.63",
    authors: ["Alex"],
    date: "2021-07-14",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "I-6",
    time: "10.90",
    vsRta: "-0.71",
    authors: ["caleb"],
    date: "2026-01-26",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "I-8",
    time: "21.13",
    vsRta: "-0.58",
    authors: ["Elite Runner"],
    date: "2022-02-20",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "I-9",
    time: "25.04",
    vsRta: "-13.03",
    authors: ["charlie"],
    date: "2025-01-25",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "Pro A-0",
    time: "42.46",
    vsRta: "-2.52",
    authors: ["Schmaniol"],
    date: "2021-11-15",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "Pro A-1",
    time: "20.41",
    vsRta: "-35.01",
    authors: ["mufattmf", "Bice"],
    date: "2026-03-20",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "Pro A-3",
    time: "54.97",
    vsRta: "-1.96",
    authors: ["Alex", "Niro"],
    date: "2021-08-12",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "Pro A-6",
    time: "52.84",
    vsRta: "-13.00",
    authors: ["ezmTAS"],
    date: "2025-03-16",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "Pro A-7",
    time: "48.98",
    vsRta: "-3.52",
    authors: ["mufattmf"],
    date: "2024-07-14",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "Pro A-8",
    time: "33.49",
    vsRta: "-34.57",
    authors: ["Bice"],
    date: "2022-12-01",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "Pro A-9",
    time: "1:14.76",
    vsRta: "0.68",
    authors: ["angry_birds_45"],
    date: "2021-07-26",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "Bonus A-1",
    time: "31.39",
    vsRta: "-0.54",
    authors: ["angry_birds_45"],
    date: "2021-08-02",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "Bonus A-5",
    time: "25.56",
    vsRta: "-0.56",
    authors: ["angry_birds_45"],
    date: "2021-09-20",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "Bonus A-6",
    time: "27.22",
    vsRta: "-0.45",
    authors: ["mufattmf"],
    date: "2023-08-01",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "Bonus B-0",
    time: "25.24",
    vsRta: "-0.57",
    authors: ["angry_birds_45"],
    date: "2021-09-19",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "Bonus B-2",
    time: "23.61",
    vsRta: "-0.32",
    authors: ["BdcapTAS"],
    date: "2024-10-07",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "Bonus B-3",
    time: "18.53",
    vsRta: "-0.40",
    authors: ["dimi"],
    date: "2021-09-21",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "Bonus B-4",
    time: "25.19",
    vsRta: "-0.23",
    authors: ["angry_birds_45"],
    date: "2021-08-30",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "Bonus B-7",
    time: "25.58",
    vsRta: "-0.22",
    authors: ["Ibozz91", "threadd"],
    date: "2025-01-13",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
  {
    track: "Bonus B-8",
    time: "24.71",
    vsRta: "-0.31",
    authors: ["angry_birds_45"],
    date: "2021-09-18",
    links: {
      video: "",
      replay: "",
      inputs: "",
    },
  },
    ],
  },
  {
    slug: "tmn-remakes",
    name: "TMN Remakes",
    description: "Remade TMN tracks with updated TAS records.",
    entries: [
      {
        track: "Remake A01 - Race",
        time: "0:32.45",
        vsRta: "-0.22",
        authors: ["TrackMaster"],
        date: "2026-04-10",
        links: {
          video: "https://youtu.be/example-video-remake",
          replay: "https://drive.google.com/example-replay-remake",
          inputs: "https://your-site.example/inputs/remake-a01",
        },
      },
    ],
  },
  {
    slug: "tmuf",
    name: "TMUF",
    description: "Leaderboards for TMUF tracks.",
    entries: [
      {
        track: "A01 - Race",
        time: "0:29.58",
        vsRta: "-0.15",
        authors: ["SpeedFox"],
        date: "2026-03-22",
        links: {
          video: "https://youtu.be/example-video-3",
          replay: "https://drive.google.com/example-replay-3",
          inputs: "https://your-site.example/inputs/tmuf-a01",
        },
      },
    ],
  },
  {
    slug: "startrack",
    name: "StarTrack",
    description: "StarTrack campaign TAS leaderboards.",
    entries: [
      {
        track: "Star01 - Race",
        time: "0:45.67",
        vsRta: "+0.05",
        authors: ["StarRunner"],
        date: "2026-03-15",
        links: {
          video: "https://youtu.be/example-video-star",
          replay: "https://drive.google.com/example-replay-star",
          inputs: "https://your-site.example/inputs/star01",
        },
      },
    ],
  },
  {
    slug: "tms",
    name: "TMS",
    description: "TMS tracks with TAS records.",
    entries: [
      {
        track: "S01 - Race",
        time: "0:38.90",
        vsRta: "-0.30",
        authors: ["SunrisePro"],
        date: "2026-03-08",
        links: {
          video: "https://youtu.be/example-video-tms",
          replay: "https://drive.google.com/example-replay-tms",
          inputs: "https://your-site.example/inputs/tms-s01",
        },
      },
    ],
  },
  {
    slug: "tmo",
    name: "TMO",
    description: "Original TM tracks TAS leaderboards.",
    entries: [
      {
        track: "O01 - Race",
        time: "0:42.12",
        vsRta: "-0.50",
        authors: ["OriginalAce"],
        date: "2026-02-28",
        links: {
          video: "https://youtu.be/example-video-tmo",
          replay: "https://drive.google.com/example-replay-tmo",
          inputs: "https://your-site.example/inputs/tmo-o01",
        },
      },
    ],
  },
  {
    slug: "demo",
    name: "Demo",
    description: "Demo tracks with TAS records.",
    entries: [
      {
        track: "Demo01 - Race",
        time: "0:25.34",
        vsRta: "-0.10",
        authors: ["DemoKing"],
        date: "2026-02-20",
        links: {
          video: "https://youtu.be/example-video-demo",
          replay: "https://drive.google.com/example-replay-demo",
          inputs: "https://your-site.example/inputs/demo01",
        },
      },
    ],
  },
  {
    slug: "tm2",
    name: "TM2",
    description: "TM2 tracks TAS leaderboards.",
    entries: [
      {
        track: "TM2-01 - Race",
        time: "0:50.56",
        vsRta: "+0.20",
        authors: ["TM2Expert"],
        date: "2026-02-10",
        links: {
          video: "https://youtu.be/example-video-tm2",
          replay: "https://drive.google.com/example-replay-tm2",
          inputs: "https://your-site.example/inputs/tm2-01",
        },
      },
    ],
  },
];
