
export type TrackInfo = {
  id: number;
  category: string;
  environment: string;
};

export const tmxTrackIds: Record<string, TrackInfo> = {
  "A01-Race": { id: 2233, category: "White", environment: "Stadium" },
  "A02-Race": { id: 2236, category: "White", environment: "Stadium" },
  "A03-Race": { id: 2239, category: "White", environment: "Stadium" },
  "A04-Acrobatic": { id: 2242, category: "White", environment: "Stadium" },
  "A05-Race": { id: 2245, category: "White", environment: "Stadium" },
  "A06-Obstacle": { id: 2248, category: "White", environment: "Stadium" },
  "A07-Race": { id: 2251, category: "White", environment: "Stadium" },
  "A08-Endurance": { id: 2254, category: "White", environment: "Stadium" },
  "A09-Race": { id: 2257, category: "White", environment: "Stadium" },
  "A10-Acrobatic": { id: 2260, category: "White", environment: "Stadium" },
  "A11-Race": { id: 2263, category: "White", environment: "Stadium" },
  "A12-Speed": { id: 2266, category: "White", environment: "Stadium" },
  "A13-Race": { id: 2269, category: "White", environment: "Stadium" },
  "A14-Race": { id: 2272, category: "White", environment: "Stadium" },
  "A15-Speed": { id: 2275, category: "White", environment: "Stadium" },
  "B01-Race": { id: 2282, category: "Green", environment: "Stadium" },
  "B02-Race": { id: 2285, category: "Green", environment: "Stadium" },
  "B03-Race": { id: 2288, category: "Green", environment: "Stadium" },
  "B04-Acrobatic": { id: 2291, category: "Green", environment: "Stadium" },
  "B05-Race": { id: 2294, category: "Green", environment: "Stadium" },
  "B06-Obstacle": { id: 2297, category: "Green", environment: "Stadium" },
  "B07-Race": { id: 2300, category: "Green", environment: "Stadium" },
  "B08-Endurance": { id: 2303, category: "Green", environment: "Stadium" },
  "B09-Acrobatic": { id: 2306, category: "Green", environment: "Stadium" },
  "B10-Speed": { id: 2309, category: "Green", environment: "Stadium" },
  "B11-Race": { id: 2312, category: "Green", environment: "Stadium" },
  "B12-Race": { id: 2315, category: "Green", environment: "Stadium" },
  "B13-Obstacle": { id: 2318, category: "Green", environment: "Stadium" },
  "B14-Speed": { id: 2321, category: "Green", environment: "Stadium" },
  "B15-Race": { id: 2324, category: "Green", environment: "Stadium" },
  "C01-Race": { id: 2328, category: "Blue", environment: "Stadium" },
  "C02-Race": { id: 2331, category: "Blue", environment: "Stadium" },
  "C03-Acrobatic": { id: 2334, category: "Blue", environment: "Stadium" },
  "C04-Race": { id: 2337, category: "Blue", environment: "Stadium" },
  "C05-Endurance": { id: 2340, category: "Blue", environment: "Stadium" },
  "C06-Speed": { id: 2343, category: "Blue", environment: "Stadium" },
  "C07-Race": { id: 2346, category: "Blue", environment: "Stadium" },
  "C08-Obstacle": { id: 2349, category: "Blue", environment: "Stadium" },
  "C09-Race": { id: 2352, category: "Blue", environment: "Stadium" },
  "C10-Acrobatic": { id: 2355, category: "Blue", environment: "Stadium" },
  "C11-Race": { id: 2358, category: "Blue", environment: "Stadium" },
  "C12-Obstacle": { id: 2361, category: "Blue", environment: "Stadium" },
  "C13-Race": { id: 2364, category: "Blue", environment: "Stadium" },
  "C14-Endurance": { id: 2367, category: "Blue", environment: "Stadium" },
  "C15-Speed": { id: 2370, category: "Blue", environment: "Stadium" },
  "D01-Race": { id: 2375, category: "Red", environment: "Stadium" },
  "D02-Race": { id: 2378, category: "Red", environment: "Stadium" },
  "D03-Acrobatic": { id: 2381, category: "Red", environment: "Stadium" },
  "D04-Race": { id: 2423, category: "Red", environment: "Stadium" },
  "D05-Race": { id: 2425, category: "Red", environment: "Stadium" },
  "D06-Obstacle": { id: 2427, category: "Red", environment: "Stadium" },
  "D07-Race": { id: 2429, category: "Red", environment: "Stadium" },
  "D08-Speed": { id: 2431, category: "Red", environment: "Stadium" },
  "D09-Obstacle": { id: 2433, category: "Red", environment: "Stadium" },
  "D10-Race": { id: 2435, category: "Red", environment: "Stadium" },
  "D11-Acrobatic": { id: 2437, category: "Red", environment: "Stadium" },
  "D12-Speed": { id: 2439, category: "Red", environment: "Stadium" },
  "D13-Race": { id: 2441, category: "Red", environment: "Stadium" },
  "D14-Endurance": { id: 2443, category: "Red", environment: "Stadium" },
  "D15-Endurance": { id: 2445, category: "Red", environment: "Stadium" },
  "E01-Obstacle": { id: 2447, category: "Black", environment: "Stadium" },
  "E02-Endurance": { id: 2449, category: "Black", environment: "Stadium" },
  "E03-Endurance": { id: 2451, category: "Black", environment: "Stadium" },
  "E04-Obstacle": { id: 2454, category: "Black", environment: "Stadium" },
  "E05-Endurance": { id: 2455, category: "Black", environment: "Stadium" },

  "A02 - No Cut": { id: 9421268, category: "White", environment: "Stadium" },
  "A05 - No Cut": { id: 7712299, category: "White", environment: "Stadium" },
  "A06 - No Cut": { id: 7712302, category: "White", environment: "Stadium" },
  "A08 - No Cut": { id: 7712307, category: "White", environment: "Stadium" },
  "A09 - No Cut": { id: 7712311, category: "White", environment: "Stadium" },
  "A12 - No Cut": { id: 7712315, category: "White", environment: "Stadium" },
  "A13 - No Cut": { id: 7712321, category: "White", environment: "Stadium" },
  "A14 - No Cut": { id: 7712327, category: "White", environment: "Stadium" },
  "A15 - No Cut": { id: 7712330, category: "White", environment: "Stadium" },
  "B02 - No Cut": { id: 7712333, category: "Green", environment: "Stadium" },
  "B03 - No Cut": { id: 8807356, category: "Green", environment: "Stadium" },
  "B05 - No Cut": { id: 7712336, category: "Green", environment: "Stadium" },
  "B07 - No Cut": { id: 7712339, category: "Green", environment: "Stadium" },
  "B08 - No Cut": { id: 7712342, category: "Green", environment: "Stadium" },
  "B12 - No Cut": { id: 7712347, category: "Green", environment: "Stadium" },
  "C04 - No Cut": { id: 7712353, category: "Blue", environment: "Stadium" },
  "C07 - No Cut": { id: 7712356, category: "Blue", environment: "Stadium" },
  "C09 - No Cut": { id: 7712361, category: "Blue", environment: "Stadium" },
  "C10 - No Cut": { id: 7712365, category: "Blue", environment: "Stadium" },
  "C12 - No Cut": { id: 7712369, category: "Blue", environment: "Stadium" },
  "C14 - No Cut": { id: 7712372, category: "Blue", environment: "Stadium" },
  "D02 - No Cut": { id: 7712378, category: "Red", environment: "Stadium" },
  "D03 - No Cut": { id: 8807365, category: "Red", environment: "Stadium" },
  "D04 - No Cut": { id: 7712381, category: "Red", environment: "Stadium" },
  "D05 - No Cut": { id: 7712386, category: "Red", environment: "Stadium" },
  "D06 - No Cut": { id: 8807369, category: "Red", environment: "Stadium" },
  "D07 - No Cut": { id: 7712390, category: "Red", environment: "Stadium" },
  "D09 - No Cut": { id: 10908007, category: "Red", environment: "Stadium" },
  "D10 - No Cut": { id: 7712393, category: "Red", environment: "Stadium" },
  "D11 - No Cut": { id: 7712396, category: "Red", environment: "Stadium" },
  "D12 - No Cut": { id: 7712399, category: "Red", environment: "Stadium" },
  "D14 - No Cut": { id: 7712402, category: "Red", environment: "Stadium" },
  "D15 - No Cut": { id: 7712405, category: "Red", environment: "Stadium" },
  "E02 - No Cut": { id: 7712408, category: "Black", environment: "Stadium" },
  "E03 - No Cut": { id: 7712411, category: "Black", environment: "Stadium" },
  "E04 - No Cut": { id: 7712414, category: "Black", environment: "Stadium" },


  
};
